
POST http://localhost:3000/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/jpg

< ./labeled_images/Thor/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
